# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IMMhdqJrmcaOmA3JiN5no2w5IDs1XARq
"""

pip install py-enigma

from enigma.machine import EnigmaMachine

# setup machine according to specs from a daily key sheet:

for i in range(1,20):
  for j in range(1,20):

    machine = EnigmaMachine.from_key_sheet(
          rotors='I II III',
          reflector='B',
          ring_settings=[1, 17, 15],
          plugboard_settings='AV BS CG DL FU HZ IN KM OW RX')

    # set machine initial starting position
    machine.set_display('WXC')

    # decrypt the message key
    msg_key = machine.process_text('KCH')

    # decrypt the cipher text with the unencrypted message key
    machine.set_display(msg_key)

    ciphertext = 'DPIWPOLLFEUPIKAKLQLC'
    plaintext = machine.process_text(ciphertext)
    # if (plaintext == "THISISNOTGONNABEEASY"):
    #   print (i,j)
print(plaintext)